//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHUberTrips.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHUberSpaceEntities : DbContext
    {
        public SHUberSpaceEntities()
            : base("name=SHUberSpaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SHUberCustomer> SHUberCustomers { get; set; }
        public virtual DbSet<SHUberDriversSpace> SHUberDriversSpaces { get; set; }
        public virtual DbSet<SHUberJourney> SHUberJourneys { get; set; }
    }
}
